### ISSUE TITLE
Is there any options to draw a undirected graph

### ISSUE THREAD

**Issue by GoBigorGoHome** [LucaCappelletti94/adigraph#2]
I think it should be easy to get an undirected version if it is possible to draw a directed one with this package. So, is there any option that allows one to draw an undirected graph?

**Comment by LucaCappelletti94** [comment]
Yes, it is in the documentation. I've actually added this recently (about a week ago) so you should check the package version that you are using.

I'll add a working minimal example here as soon as I get my morning coffee :)

**Comment by LucaCappelletti94** [comment]
Here I am! So basically you can test the version by compiling something like:
```tex
\documentclass{report}
\usepackage{adigraph}
\begin{document}
\AdigraphVersionNumber
\end{document}
```
If the version you get is lower than `1.6.0`, upgrade your `adigraph` package by running:
```sh
[sudo if needed] tlmgr update adigraph
```
If you get as version at least the `1.6.0`, you can make a undirected graph with a custom style:
```tex
\documentclass{report}
\usepackage{adigraph}
\begin{document}
\begin{figure}
  \NewAdigraph{myCustomEdgesAdigraph}{
    s:0,0;
    1:2,2;
    3:2,-2;
    2:6,2;
    4:6,-2;
    t:8,0;
  }{
    s,1:25;
    s,3:25;
    3,4:25;
    1,2:35;
    2,t:20;
    4,t:30;
    3,1:10;
    4,2:10;
    2,3:15::near start;
    4,1:5::near start;
  }[-]
  \myCustomEdgesAdigraph{}
\end{figure}
\end{document}
```
By compiling this example, which is taken [directly from the documentation](https://github.com/LucaCappelletti94/adigraph/blob/master/adigraph_documentation.pdf), you should a graph like the following:
![Undirected graph](https://user-images.githubusercontent.com/7738570/49574133-f5fc2b00-f93f-11e8-89cb-a5af2d41f996.jpg)

If you need any further help don't hesitate to ask.

**Comment by GoBigorGoHome** [comment]
Thank you very much.
This is really an awesome package for drawing graphs with a style that I always want.

In fact, I did get the latest version of this package, but I didn't read through the document, I simply searched for the word "undirected" in the document and did not find anything relevant (since you used the words "non oriented" :P).

So, this time I do read a bit more of the package document and find something that might be improved.

The paragraph under the title of section 3.5 says
> We set its nodes with the following syntax: *<node name: x coordinate, y
> coordinate, color, edge width: label>*.

the word "nodes" seems like a typo and should be "edges", also there is no such an example that the x,y coordinates are set for an edge. So I think something may be wrong with this paragraph, and you may check it out.

**Comment by LucaCappelletti94** [comment]
Ok, I have fixed the copy paste errors, I wrote the documentation in haste so I guess a few errors will be there somewhere. The examples however are surely correct as they get tested at each compilation.

**Comment by GoBigorGoHome** [comment]
The pdf documentation is not updated. It might need to be regenerated.

**Comment by LucaCappelletti94** [comment]
The new documentation has been committed with the fixes and is available [here](https://github.com/LucaCappelletti94/adigraph/blob/b454ed5340d1ff8aaba87444dd063257f22e9dd7/adigraph_documentation.pdf), tough there might be more errors lying around.

If you find any I'd be more than happy to fix them, just let me know!

**Comment by GoBigorGoHome** [comment]
I am afraid the documentation is NOT new, but remain unchanged.

![2dzo82 b yedo g 3 a9](https://user-images.githubusercontent.com/9896288/49648468-e58fa180-fa60-11e8-8e62-bfe6c2cacee2.png)

**Comment by LucaCappelletti94** [comment]
You are absolutely right, I have recompiled the documentation just now.

**Comment by LucaCappelletti94** [comment]
You might like to know that I have completed the new version of adigraph and introduced the python library [pyadigraph](https://github.com/LucaCappelletti94/pyadigraph), which convert networkx graphs to latex automatically.
