### ISSUE TITLE
Nodes same size

### ISSUE THREAD

**Issue by leomayer** [LucaCappelletti94/adigraph#3]
Is it possible to adjust the nodes size in a way that they have all the same size? This applies especially when the text is not just one single character but longer (and multi line [e. g. `{\shortstack{test\\multi\\line}}`). 

According to https://tex.stackexchange.com/a/349344/48642 it shouldn't be that hard to accomplish. 

BTW: I personally don't see a reason why they should have different size at all!

**Comment by LucaCappelletti94** [comment]
I would have sworn that all nodes have by default the same size, could you share an example where that does not happen?

**Comment by LucaCappelletti94** [comment]
Oh ok, I see, I'll see how to add a parameter for the minimum node size.

**Comment by leomayer** [comment]
So there are two approaches. Either set minimum size or set all the same size.

Perhaps one could use a simple command to change the size.
For the second approach I added the link.

I personally would like more to have the second approach although I can see benefits with the first one.

**Comment by leomayer** [comment]
[patchForMinimalNodeSize.txt](https://github.com/LucaCappelletti94/adigraph/files/6450153/patchForMinimalNodeSize.txt)

I have no clue how to commit something. Please find enclosed a patch how to set the minimal size of a node. 

Perhaps it would be possible to run a command and calculate the size out of the list of nodes. Would be great. But until that this patch would be sufficient.

Usage in the document: `\settowidth{\AdigraphNodeMinSize}{adjusted textsize}`

BTW: Don't forget to update the documentation. I can provide as well an update if you like - in case you accept that patch :-)

**Comment by LucaCappelletti94** [comment]
Sure @leomayer, I am inserting your patch.

**Comment by LucaCappelletti94** [comment]
I have inserted [your updatein the new min_size branch](https://github.com/LucaCappelletti94/adigraph/tree/min_size) and the [documentation](https://github.com/LucaCappelletti94/adigraph/blob/min_size/adigraph_documentation.pdf).

Do let me know if you think it is okay. If so, I will publish this to the CTAN repository and when the next minor latex release is done it'll be integrated. Consider that, if you'd like to use Overleaf, they will include this only after a few minor latex release.

**Comment by leomayer** [comment]
I happy you accept it and include it. Some remarks

* Code
    * as soon as you set the minimum size it will effect all the ongoing graphs. If the user wants to change it back (s)he has to set it manually to the default value of `2em`. I would mention this in the documentation.
    * I see the current approach as the minimal one to achieve the goal. If someone is willing to volunteer one could easily (?) iterate over the nodes and change the length to the maximum value. But this has the same issue as above, i.e. all ongoing graphs have the same size
* Documentation
    - I would change the release version
    - Your documentation has some problems with `syntax` - just search for it and you'll see. Seems like Spanish is your mother tongue :-)
    - I would change the sample to something like below. To make the benefit more clear.
    - Your package facilitates perfectly (state) transition diagrams, like [probabilites in math](https://www.rhetos.de/html/lex/uebergangsdiagramm.htm),  [transition in business](http://www.zenofbpm.com/styled-28/styled-41/) or [transitions for accounts](https://www.researchgate.net/figure/A-state-transition-diagram-for-a-Stream-X-machine-modelling-a-bank-account-Web-service_fig1_220774658). Perhaps you could add a sample (or replace the current one) and update the CTAN description of it. 
    - CTAN: There is the possiblity to add a screenshot to the [description](https://ctan.org/pkg/pst-dbicons). Perhaps you could add one ([with two samples](https://ctan.org/pkg/pst-dbicons)?) as well.
* Release
    - Looking forward to see a release
Last q: Is the package is in maintance mode or actively continued, e.g. dashed edges on particular edges? Would be another idea.

```
    \setlength{\AdigraphNodeMinSize}{5em}
    \NewAdigraph{myAdigraph}{
    	s:0,0:{\shortstack{start\\point}};
    	1:2,2;
    	3:2,-2;
    	2:6,2;
    	4:6,-2;
    	t:8,0:{\shortstack{end\\point}};
    }{
    	s,1:25;
    	s,3:25;
    	3,4:25;
    	1,2:35;
    	2,t:20;
    	4,t:30;
    	3,1:10;
    	4,2:10;
    	2,3:15::near start;
    	4,1:5::near start;
    }
    \myAdigraph{
    	s,3,4,2,t::green;
    	s,1,2::red;
    }

**Comment by leomayer** [comment]
Any progress on this issue? Any releases?

**Comment by dreamjz** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.unbaiat, @SpaceyLad, @Leandros, @jzarca01, @mahmoudkandeel, @simonw, @YXGuan, @sockusminimus, @amirhnajafiz, @Cor3Zer0, @gabrielcorado, @slipperypenguin, @deadanon, @jack-fireworkhq, @newsworthy39, @SuCicada, @koi-LANG21, @gruberdev, @gris-gris, @inspicere

**Comment by LucaCappelletti94** [comment]
Oh well, thanks to that spammer I rediscovered this forgotten issue. Sorry for the long delay, looking into it now.

**Comment by LucaCappelletti94** [comment]
Submitted the contribution to CTAN.
